NutritionApi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
]

book/urls.py
from django.urls import path
from book import views

app_name = 'book'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:age>/', views.show_age, name='show_age'),
    path('name/<str:name>/', views.show_name, name='show-name'),
    path('home/', views.home, name="home"),
    path('search/', views.search, name="search"),
    path('about/', views.about, name="about"),
]

book/models.py
from django.db import models

# Create your models here.

book/views.py
from django.shortcuts import render
from django.http import HttpResponse

def show_age(request, age):
    return HttpResponse("I am %s years old." % age)

def show_name(request, name):
    return HttpResponse("Hello, I am showing the name - %s" % name)

def index(request):
    my_dict = {'insert_me': "Hello I am from views.py!"}
    return render(request, 'book/index.html', context=my_dict)

def home(request):
    return render(request, 'book/home.html')

def search(request):
    return render(request, 'book/search.html')

def about(request):
    return render(request, 'book/about.html')

core/user/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

templates/book/about.html
<!DOCTYPE html>
{% extends "book/base.html" %}

{% block title %} About {% endblock %}

{% block content %}

<h3>Welcome to About Page</h3>

{% endblock %}

templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %} <!-- Title Name -->  #}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class=container>
    <ul class= "nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'book:home' %}">Home</a></li>
      <li><a class="navbar-brand" href="{% url 'book:search' %}">Search</a></li> 
      <li><a class="navbar-brand" href="{% url 'book:about' %}">About</a></li>
    </ul>
  </div>
</nav> 

  
<div class="container">
  {% block content %}<!-- Page content   -->{% endblock %}
</div>

</body>

templates/book/home.html
<!DOCTYPE html>
{% extends "book/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}

<h3>Welcome to Home Page</h3>

{% endblock %}

templates/book/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>My First Application</title>
</head>
<body>
    <h1>Hello this is index.html!</h1>
    {{insert_me}}
    <a href = "{% url 'book:show-name' name='vlad' %}">Name</a>
</body>
</html>

templates/book/search.html
<!DOCTYPE html>
{% extends "book/base.html" %}

{% block title %} Search {% endblock %}

{% block content %}

<h3>Welcome to Search Page</h3>

{% endblock %}